### ISSUE TITLE
i am facing unknown error please help !

### ISSUE THREAD

**Issue by Reddy2103** [whoami8080/Strome-breaker#2]
t=2021-10-27T13:10:49-0400 lvl=warn msg="failed to check for update" obj=updater err="Post \"https://update.equinox.io/check\": context deadline exceeded"
00t=2021-10-27T13:10:54-0400 lvl=eror msg="failed to reconnect session" obj=csess id=e957c36b7985 err="dial tcp: i/o timeout"
t=2021-10-27T13:11:05-0400 lvl=eror msg="failed to reconnect session" obj=csess id=e957c36b7985 err="dial tcp: i/o timeout"
Traceback (most recent call last):
  File "/home/pihacker/Storm-Breaker/Storm-Breaker.py", line 50, in <module>
    localhost.micro()
  File "/home/pihacker/Storm-Breaker/modules/localhost.py", line 152, in micro
    a = ngrok.connect(6565,"http",auth_token=token)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 251, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/ngrok.py", line 162, in get_ngrok_process
    return process.get_process(pyngrok_config)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/process.py", line 295, in get_process
    return _start_process(pyngrok_config)
  File "/usr/local/lib/python3.9/dist-packages/pyngrok/process.py", line 464, in _start_process
    raise PyngrokNgrokError("The ngrok process errored on start: {}.".format(ngrok_process.startup_error),
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start: dial tcp: i/o timeout.

**Comment by spyfox46** [comment]
i have same problms 2
